apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    {{- include "counter-app.postgresLabels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.database.name }}
  POSTGRES_USER: {{ .Values.database.user }}
