{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    {{- include "counter-app.postgresLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  capacity:
    storage: {{ .Values.postgres.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgres.persistence.path | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    {{- include "counter-app.postgresLabels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
