apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "counter-app.postgresLabels" . | nindent 4 }}
type: Opaque
data:
  # Base64 encoded password
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc }}
